### ISSUE TITLE
Problem since new commits ?

### ISSUE THREAD

**Issue by Dolu89** [wspl/creeper#1]
Hi,

I just copy paste your example code (hacker_news). Yesterday, it worked. Today with the new sources, it doesn't work anymore :(

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x45cdb6]

goroutine 1 [running]:
panic(0x65db60, 0xc42000c190)
        /opt/go/src/runtime/panic.go:500 +0x1a1
github.com/wspl/creeper.(*Node).Value(0x0, 0x0, 0xc42001acd0, 0x0, 0xc4200340b8)
        /home/ubuntu/workspace/src/github.com/wspl/creeper/node.go:118 +0x26
github.com/wspl/creeper.(*Creeper).Each(0xc42001acd0, 0x6cc428)
        /home/ubuntu/workspace/src/github.com/wspl/creeper/creeper.go:74 +0x8b
main.main()
        /home/ubuntu/workspace/main.go:12 +0x73
exit status 2
```

(A simple println alone works :) )

**Comment by wspl** [comment]
It is a bug caused by new feature `primary key`. Now I fixed it.
Thanks for your report.
